ASSIGNMENT 1
Basic Data Exploration and Cleaning Using Pandas

Submitted By:

Devansh Saini_MMDU

Role:

Data Engineer Intern

Objective:

The primary goal of this task is to utilize the Python Pandas library to systematically preprocess and understand a raw dataset. This workflow encompasses importing data from a CSV file, analyzing its underlying structure and data types, mitigating missing or null values, and eliminating duplicate records. Furthermore, it involves applying conditional filters, engineering new features through derived columns, and ultimately exporting the refined dataset to ensure it is structured and ready for downstream analytical processes

Import Required Libraries

In [1]:
import pandas as pd

print("Pandas library imported successfully!")

Pandas library imported successfully!

Question 1: Load a CSV Dataset into a Pandas DataFrame

In [2]:
df = pd.read_csv("C:\\Users\\Acer\\Desktop\\Combined_dataset.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

Question 2: Explore Data (head/tail, shape, columns, data types)

In [3]:
# 2. Explore data
print("--- First 5 Rows (Head) ---")
display(df.head())

print("\n--- Last 5 Rows (Tail) ---")
display(df.tail())

print("\n--- Dataset Shape (Rows, Columns) ---")
print(df.shape)

print("\n--- Column Names ---")
print(df.columns.tolist())

print("\n--- Data Types ---")
print(df.dtypes)

--- First 5 Rows (Head) ---

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

--- Last 5 Rows (Tail) ---

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

--- Dataset Shape (Rows, Columns) ---
(1000, 24)

--- Column Names ---
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

--- Data Types ---
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

Question 3: Handle Missing Values (identify, fill/drop)

In [14]:

print("--- Missing Values Count Before Cleaning ---")
print(df.isnull().sum())

if 'price' in df.columns and 'quantity' in df.columns:
    df.dropna(subset=['price', 'quantity'], inplace=True)


df.fillna('Unknown', inplace=True)

print("\n--- Missing Values Count After Cleaning ---")
print(df.isnull().sum())

--- Missing Values Count Before Cleaning ---
product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
estimated_revenue         0
dtype: int64

--- Missing Values Count After Cleaning ---
product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
estimated_revenue         0
dtype: int64

Question 4: Perform Basic Operations (filter rows, select columns)

In [9]:
sales_data = df
if 'ratings_count' in sales_data.columns:

    sales_data['ratings_count'] = pd.to_numeric(sales_data['ratings_count'], errors='coerce')
    sales_data = sales_data[sales_data['ratings_count'] > 0]

columns_to_select = ['title', 'initial_price', 'final_price', 'ratings_count']

existing_columns = [col for col in columns_to_select if col in sales_data.columns]

if existing_columns:
    selected_columns = sales_data[existing_columns]
    
    print("\n--- Subset of Selected Columns ---")
    display(selected_columns.head())

--- Subset of Selected Columns ---

            title  initial_price  final_price  ratings_count
0     Lino Perros           3995  "₹3,995.00"             15
1  Tommy Hilfiger           2899  "₹2,899.00"             67
2           Lavie           2999  "₹2,999.00"            226
3          F Gear           1675  "₹1,675.00"           1052
4       MYTRIDENT           2899  "₹2,899.00"             12

Question 5: Remove Duplicates

In [10]:
# 5. Remove duplicates
print(f"Shape before dropping duplicates: {df.shape}")

df.drop_duplicates(inplace=True)

print(f"Shape after dropping duplicates: {df.shape}")

Shape before dropping duplicates: (1000, 24)
Shape after dropping duplicates: (1000, 24)

Question 6: Create a Derived Column (total_amount = price * quantity)

In [12]:
sales_data = df

col_price = 'initial_price'
col_qty = 'ratings_count'

if col_price in sales_data.columns and col_qty in sales_data.columns:
    sales_data[col_price] = pd.to_numeric(sales_data[col_price], errors='coerce')
    sales_data[col_qty] = pd.to_numeric(sales_data[col_qty], errors='coerce')
    
    sales_data['estimated_revenue'] = sales_data[col_price] * sales_data[col_qty]
    
    print("\n--- DataFrame with Derived 'estimated_revenue' Column ---")
    display(sales_data[[col_price, col_qty, 'estimated_revenue']].head())
    
else:
    print(f"Warning: Missing required columns. Could not find '{col_price}' or '{col_qty}'.")

--- DataFrame with Derived 'estimated_revenue' Column ---

   initial_price  ratings_count  estimated_revenue
0           3995             15              59925
1           2899             67             194233
2           2999            226             677774
3           1675           1052            1762100
4           2899             12              34788

Question 7: Save the Cleaned Dataset as a New CSV File

In [13]:
output_filename = 'cleaned_dataset.csv'
df.to_csv(output_filename, index=False)

print(f"Cleaned dataset successfully saved as '{output_filename}'!")

Cleaned dataset successfully saved as 'cleaned_dataset.csv'!